################################### Default Configuration ############################
baseurl = "https://redstickchick.com"
title = "Red Stick Chick"
theme = "vex-hugo"
# post excerpt
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [true] # disable language from here
favicon = "images/favicon.png"
